/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package net.tiosm;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="Tiosm", id="net.tiosm")
public class TiosmModule extends KrollModule {
	@Kroll.constant
	public static final int OSMARENDER = 0;
	@Kroll.constant
    public static final int MAPNIK = 1; // this is default
    @Kroll.constant
    public static final int CYCLEMAP = 2;
    @Kroll.constant
    public static final int PUBLIC_TRANSPORT = 3;
    @Kroll.constant
    public static final int BASE = 4;
	@Kroll.constant
    public static final int TOPO = 5;
    @Kroll.constant
    public static final int HILLS = 6;
	@Kroll.constant
    public static final int CLOUDMADESTANDARDTILES = 7;
    @Kroll.constant
    public static final int CLOUDMADESMALLTILES = 8;
    @Kroll.constant
    public static final int MAPQUESTOSM = 9;

	// Standard Debugging variables
	private static final String LCAT = "TiosmModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TiosmModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public String example() {
		Log.d(LCAT, "example called");
		return "hello world";
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(LCAT, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}

}

