/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package org.appcelerator.openstreetmap;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;

// This proxy can be created by calling MapViewModule.createMapView()
@Kroll.proxy(creatableInModule=MapViewModule.class)
public class MapViewProxy extends TiViewProxy {
	// Standard Debugging variables
	private static final String LCAT = "OpenStreetMapViewProxy";
	private static final boolean DBG = TiConfig.LOGD;
	
	private KrollDict location;
	
	// Constructor
	public MapViewProxy(TiContext tiContext) {
		super(tiContext);
	}
	
	// Methods
	@Override
	public TiUIView createView(Activity activity) {
		if (DBG) Log.d(LCAT, "createView");
		return new TiMapView(this);
	}
	
	/*
	@Kroll.method
	public void addAnnotation(AnnotationProxy annotation) {
		if (DBG) Log.d(LCAT, "not implemented");
	}*/

	@Kroll.method
	public void deselectAnnotation(Object[] args) {
		if (DBG) Log.d(LCAT, "not implemented");
	}

	@Kroll.method
	public void removeAllAnnotations() {
		if (DBG) Log.d(LCAT, "not implemented");
	}

	@Kroll.method
	public void removeAnnotation(Object arg) {
		if (DBG) Log.d(LCAT, "not implemented");
	}

	@Kroll.method
	public void selectAnnotation(Object[] args) {
		if (DBG) Log.d(LCAT, "not implemented");
	}
	
	@Kroll.method
	public void setLocation(KrollDict location) {
		if (DBG) Log.d(LCAT, "not implemented");
	}

	@Kroll.method
	public void setMapType(int mapType) {
		if (DBG) Log.d(LCAT, "not implemented");
	}
	
	@Kroll.method
	public void zoom(int delta) {
		if (DBG) Log.d(LCAT, "not implemented");
	}
	
}